# Generated by Django 2.1.7 on 2019-02-14 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.CharField(blank=True, default='', max_length=500)),
                ('end_date', models.DateField()),
                ('institution', models.CharField(blank=True, default='', max_length=500)),
                ('start_date', models.DateField()),
                ('website', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('position', models.CharField(blank=True, default='', max_length=500)),
                ('start_date', models.DateField()),
                ('summary', models.TextField()),
                ('website', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('link', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('headline', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('medium', models.URLField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('summary', models.TextField()),
                ('website', models.URLField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(blank=True, default='', max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(blank=True, default='', max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('summary', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, default='', max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
