# Generated by Django 2.1.7 on 2019-02-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-end_date',)},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-end_date',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='me',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='experience',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
